apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: bookinfo-productpage4
  namespace: default
spec:
  host: test.bookinfo.com
  prefix: /4
  service: productpage.default.svc:9080
  timeout_ms: 30000
  labels:
    emissary:
      - grupo:
          - generic_key: gw_name_3
          - generic_key: default