apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: bookinfo-productpage2
  namespace: default
spec:
  host: test.bookinfo.com
  prefix: /2
  service: productpage.default.svc:9080
  timeout_ms: 30000
  labels:
    emissary:
      - grupo:
          - generic_key: gw_name_1
          - generic_key: high