apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: bookinfo-productpage
  namespace: default
spec:
  host: test.bookinfo.com
  prefix: /
  service: productpage.default.svc:9080
  timeout_ms: 30000
  labels:
    emissary:
      - grupo:
        - request_headers:
            header_name: teste
            key: foo
            