apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: ambassador
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 8080
  selector:
    service: ambassador