apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: bookinfo-productpage
  namespace: default
spec:
  host: 172.21.0.2
  prefix: /
  service: productpage.default.svc:9080
  timeout_ms: 30000
  