apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: bookinfo-productpage
  namespace: default
spec:
  host: test.bookinfo.com
  prefix: /
  service: productpage.default.svc:9080
  timeout_ms: 30000
  labels:
    emissary:
      - request_label_group:
        - x-emissary-test-allow:
          request_headers:
              key: "x-emissary-test-allow"
              header_name: "x-emissary-test-allow"