apiVersion: v1
kind: Service
metadata:
  name: productpage-norl
  labels:
    app: productpage
    service: productpage
spec:
  type: NodePort
  ports:
  - port: 9080
    name: http
    nodePort: 30007
  selector:
    app: productpage