apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit
data:
  config: |-
    domain: emissary
    descriptors:
      - key: generic_key
        value: gw_name_1
        descriptors: 
          - key: generic_key
            value: low
            rate_limit:
              unit: second
              requests_per_unit: 10
          - key: generic_key
            value: default
            rate_limit:
              unit: second
              requests_per_unit: 30
          - key: generic_key
            value: high
            rate_limit:
              unit: second
              requests_per_unit: 50
      - key: generic_key
        value: gw_name_2
        descriptors: 
          - key: generic_key
            value: low
            rate_limit:
              unit: second
              requests_per_unit: 10
          - key: generic_key
            value: default
            rate_limit:
              unit: second
              requests_per_unit: 30
          - key: generic_key
            value: high
            rate_limit:
              unit: second
              requests_per_unit: 50
      - key: generic_key
        value: gw_name_3
        descriptors: 
          - key: generic_key
            value: low
            rate_limit:
              unit: second
              requests_per_unit: 10
          - key: generic_key
            value: default
            rate_limit:
              unit: second
              requests_per_unit: 30
          - key: generic_key
            value: high
            rate_limit:
              unit: second
              requests_per_unit: 50
          
          